version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/spring-eureka-server

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - setup_remote_docker:

      # Download and cache dependencies
      - restore_cache:
          keys:
            - spring-eureka-server-{{ checksum "pom.xml" }}
            - spring-eureka-server

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-eureka-server-{{ checksum "pom.xml" }}

      - run:
          name: Compile and package
          command: mvn clean install

      - run:
         name: Docker img creation
         command: mvn docker:build

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Push to DockerHub
          command: mvn docker:push